#!/usr/bin/env python3
"""Spread is the pool mean: the binary identity, and how selection spends it.

Style reference: docs/figures/src/make_figures.py (Owain Evans-lab style --
white background, headline sentence stating the finding, real data with fat
labels, in-figure condition lines instead of a colour legend).

Run from this directory:   python3 spread-is-the-mean.py
Stdlib only.

SOURCES
  experiments/spread_supply.json
      binary_identity_check, decomposition.pool_mean, by_round,
      zero_spread_share, binary_share_of_rows, prompt_stability_across_runs.
      Read from the repo when present; the literals below are a verified copy
      so this script also runs standalone. A mismatch prints a loud warning.

  scripts/analysis_spread_supply.py -> collect()
      The per-pool counts (how many prompt-rounds landed on each of the seven
      possible pool means, overall and per round) are NOT in the JSON. They
      were regenerated by calling collect() on the raw per-candidate logs and
      histogramming pool_mean * 6. Every one of the 1,248 rows has exactly
      6 candidates, so pool_mean * 6 is an integer 0..6 on every row.
"""
import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
SUPPLY = os.path.join(ROOT, "experiments", "spread_supply.json")

# ---- palette, copied from make_figures.py -------------------------------
INK = "#1a1a1a"
BLUE = "#2867b5"       # accent / self-judge series (validated)
GREEN = "#3a7d44"      # accent / frozen-judge series (validated)
RED = "#b5342c"        # emphasis for reversal / warning text
GRAY = "#6b7684"       # recessive only (axes, muted captions) -- never a series
USER_FILL = "#cfe0f1"
ASST_FILL = "#eaf1f8"
DOC_FILL = "#fdf6e8"
KEY_FILL = "#eef5ee"

FONT = "Helvetica, Arial, sans-serif"


# ---- helpers, copied from make_figures.py -------------------------------
def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def wrap(text, width):
    words, lines, cur = text.split(), [], ""
    for w in words:
        if len(cur) + len(w) + 1 > width and cur:
            lines.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        lines.append(cur)
    return lines


def rich_text(x, y, segments, size, width, lh=1.38, weight="normal"):
    """segments: list of (text, color, bold). Wraps across segments."""
    words = []
    for text, color, bold in segments:
        for w in text.split():
            words.append((w, color, bold))
    out, line, count = [], [], 0
    for w, color, bold in words:
        if count + len(w) + 1 > width and line:
            out.append(line)
            line, count = [], 0
        line.append((w, color, bold))
        count += len(w) + 1
    if line:
        out.append(line)
    svg = []
    for i, ln in enumerate(out):
        tspans = "".join(
            f'<tspan fill="{c}" font-weight="{"bold" if b else weight}">{esc(w)} </tspan>'
            for w, c, b in ln)
        svg.append(f'<text x="{x}" y="{y + i * size * lh}" font-family="{FONT}" '
                   f'font-size="{size}">{tspans}</text>')
    return "\n".join(svg), y + len(out) * size * lh


def text_block(x, y, text, size, width, color=INK, weight="normal", lh=1.38):
    return rich_text(x, y, [(text, color, weight == "bold")], size, width, lh)


def box(x, y, w, h, fill, stroke=INK, sw=2.5, rx=8):
    return (f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" '
            f'fill="{fill}" stroke="{stroke}" stroke-width="{sw}"/>')


def arrow(x1, y1, x2, y2, sw=4, color=INK):
    return (f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{color}" '
            f'stroke-width="{sw}" marker-end="url(#arr)"/>')


DEFS = f'''<defs><marker id="arr" viewBox="0 0 10 10" refX="9" refY="5"
 markerWidth="6" markerHeight="6" orient="auto-start-reverse">
 <path d="M 0 0 L 10 5 L 0 10 z" fill="{INK}"/></marker>
<marker id="arrB" viewBox="0 0 10 10" refX="9" refY="5"
 markerWidth="6" markerHeight="6" orient="auto-start-reverse">
 <path d="M 0 0 L 10 5 L 0 10 z" fill="{BLUE}"/></marker>
<marker id="arrR" viewBox="0 0 10 10" refX="9" refY="5"
 markerWidth="6" markerHeight="6" orient="auto-start-reverse">
 <path d="M 0 0 L 10 5 L 0 10 z" fill="{RED}"/></marker></defs>'''


def svg_doc(w, h, body):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" '
            f'font-family="{FONT}">\n<rect width="{w}" height="{h}" fill="white"/>\n'
            f'{DEFS}\n{body}\n</svg>')


def txt(x, y, s, size=19, color=INK, weight="normal", anchor="start",
        style=""):
    return (f'<text x="{x}" y="{y}" font-family="{FONT}" font-size="{size}" '
            f'fill="{color}" font-weight="{weight}" text-anchor="{anchor}"'
            f'{style}>{esc(s)}</text>')


# ---- data ---------------------------------------------------------------
# Verified copy of experiments/spread_supply.json (only the fields used here).
FALLBACK = {
    "n_rows": 1248, "n_runs": 26, "n_prompts": 48,
    "zero_spread_share": 0.1891025641025641,
    "binary_share_of_rows": 1.0,
    "binary_identity_check": {"rows_checked": 1248,
                              "max_absolute_deviation": 1.1102230246251565e-16},
    "decomposition": {"pool_mean": {"prompt_share": 0.4561130301532717,
                                    "run_share": 0.5023386777539918,
                                    "round_share": 0.0019950514298453766}},
    "prompt_stability_across_runs": {
        "pool_mean": {"split_half_correlation_mean": 0.9198284955586824,
                      "ci_lo": 0.8868296424375418,
                      "ci_hi": 0.9479576825489499, "n_splits": 200}},
    "by_round": {
        "pool_mean": {"round1": {"n": 312, "mean": 0.4236111111111111},
                      "round2": {"n": 312, "mean": 0.4193376068376068},
                      "round3": {"n": 312, "mean": 0.42628205128205127},
                      "round4": {"n": 312, "mean": 0.4519230769230769}},
        "raw_spread": {"round1": {"n": 312, "mean": 0.4303466118337793},
                       "round2": {"n": 312, "mean": 0.40282037813200333},
                       "round3": {"n": 312, "mean": 0.38863294496847955},
                       "round4": {"n": 312, "mean": 0.3646324051425725}},
        "distance_of_pool_mean_from_half": {
            "round1": {"n": 312, "mean": 0.20032051282051283},
            "round2": {"n": 312, "mean": 0.23664529914529916},
            "round3": {"n": 312, "mean": 0.25641025641025644},
            "round4": {"n": 312, "mean": 0.26816239316239315}}},
}

# Regenerated with collect() in scripts/analysis_spread_supply.py: the number
# of prompt-rounds whose pool mean is k/6, for k = 0..6. N_CAND is 6 on every
# one of the 1,248 rows, so these seven levels are the only ones that exist.
N_CAND = 6
COUNTS_ALL = [189, 195, 204, 247, 234, 132, 47]          # sums to 1248
COUNTS_BY_ROUND = {                                       # each sums to 312
    1: [37, 44, 60, 85, 64, 14, 8],
    2: [45, 54, 54, 62, 58, 29, 10],
    3: [49, 55, 52, 48, 56, 41, 11],
    4: [58, 42, 38, 52, 56, 48, 18],
}


def load():
    if os.path.exists(SUPPLY):
        with open(SUPPLY) as fh:
            d = json.load(fh)
        for k, v in FALLBACK["by_round"]["raw_spread"].items():
            got = d["by_round"]["raw_spread"][k]["mean"]
            if abs(got - v["mean"]) > 1e-9:
                print(f"WARNING: embedded {k} spread {v['mean']} != file {got}")
        return d
    print("NOTE: experiments/spread_supply.json not found; using the "
          "embedded verified copy.")
    return FALLBACK


def sigma(q, n=N_CAND):
    """The identity itself: sample standard deviation of n binary scores."""
    return math.sqrt(n / (n - 1.0)) * math.sqrt(max(q * (1.0 - q), 0.0))


# ---- geometry -----------------------------------------------------------
W, H = 1700, 1566
PX0, PX1 = 210, 980                  # q = 0 .. q = 1
AY0, ATOP = 830, 490                 # sigma = 0 .. sigma = SMAX
SMAX = 0.68
BY0, BTOP = 1285, 1085               # share = 0 .. share = SHMAX
SHMAX = 0.32
AXIS_X = 150
RX0, RW = 1090, 560                  # right column


def qx(q):
    return PX0 + q * (PX1 - PX0)


def ay(s):
    return AY0 - s / SMAX * (AY0 - ATOP)


def by(share):
    return BY0 - share / SHMAX * (BY0 - BTOP)


def chip_pool(cx, cy, k, n=N_CAND, side=15, gap=4):
    """A whole pool drawn as n little squares, k of them filled."""
    total = n * side + (n - 1) * gap
    x = cx - total / 2.0
    out = []
    for i in range(n):
        fill = INK if i < k else "white"
        out.append(f'<rect x="{x + i * (side + gap):.1f}" y="{cy}" '
                   f'width="{side}" height="{side}" rx="3" fill="{fill}" '
                   f'stroke="{INK}" stroke-width="2"/>')
    return "\n".join(out)


def build():
    d = load()
    bid = d["binary_identity_check"]
    dec = d["decomposition"]["pool_mean"]
    stab = d["prompt_stability_across_runs"]["pool_mean"]
    pm = d["by_round"]["pool_mean"]
    sp = d["by_round"]["raw_spread"]
    dh = d["by_round"]["distance_of_pool_mean_from_half"]
    rounds = sorted(pm, key=lambda s: int(s.replace("round", "")))
    n_rows = sum(COUNTS_ALL)
    per_round_n = sum(COUNTS_BY_ROUND[1])
    px_per_sigma = SMAX / (AY0 - ATOP)          # what one pixel is worth
    zero_n = COUNTS_ALL[0] + COUNTS_ALL[-1]
    ends_r1 = (COUNTS_BY_ROUND[1][0] + COUNTS_BY_ROUND[1][-1]) / per_round_n
    ends_r4 = (COUNTS_BY_ROUND[4][0] + COUNTS_BY_ROUND[4][-1]) / per_round_n

    s = []

    # ---------------- headline ----------------
    head, y = rich_text(
        58, 68,
        [("Within-prompt spread", INK, True),
         ("is not a second state variable.", RED, True),
         ("With 0/1 candidate scores it is the pool mean, pushed through fixed"
          " arithmetic — and selection spends it by pushing pools to the"
          " ends of the scale.", INK, True)],
        37, 76)
    s.append(head)
    sub, y = text_block(
        58, y + 22,
        "Each pool is the six candidate answers one prompt got in one round; "
        "the judge scores each candidate 0 or 1, the pool mean q is the share "
        "it scored 1, and the spread σ is the sample standard deviation "
        "of those six scores. Every row in the corpus is scored that way, so "
        "σ carries no information the pool mean does not already carry.",
        21, 145, color=GRAY)
    s.append(sub)

    # ---------------- panel A ----------------
    s.append(txt(58, 382, "The identity, drawn: every prompt-round in the "
                          "corpus sits on one arithmetic curve", 24, INK,
                 "bold"))
    t, _ = text_block(
        58, 410,
        "Each dot is one of the seven pool compositions that can occur; its "
        "area is "
        f"how many of the {n_rows:,} prompt-rounds landed there and the label "
        f"beside it is that count. The two dots on the floor are the {zero_n} "
        f"pools ({d['zero_spread_share'] * 100:.1f}%) where all six "
        "candidates got the same score.",
        19, 106, color=GRAY)
    s.append(t)

    # recessive grid + axes
    for tick in (0.0, 0.2, 0.4, 0.6):
        yy = ay(tick)
        s.append(f'<line x1="{AXIS_X}" y1="{yy:.1f}" x2="{PX1 + 46}" '
                 f'y2="{yy:.1f}" stroke="{GRAY}" stroke-width="1" '
                 f'opacity="0.35"/>')
        s.append(txt(AXIS_X - 12, yy + 7, f"{tick:.1f}", 19, GRAY, anchor="end"))
    s.append(f'<line x1="{AXIS_X}" y1="{ATOP}" x2="{AXIS_X}" y2="{AY0}" '
             f'stroke="{GRAY}" stroke-width="2"/>')
    s.append(f'<text x="86" y="{(ATOP + AY0) / 2:.0f}" font-family="{FONT}" '
             f'font-size="20" fill="{INK}" text-anchor="middle" '
             f'transform="rotate(-90 86 {(ATOP + AY0) / 2:.0f})">'
             f'within-pool spread σ</text>')

    # the curve, as a wide band plus a hairline
    pts = []
    for i in range(0, 401):
        q = i / 400.0
        pts.append(f"{qx(q):.2f},{ay(sigma(q)):.2f}")
    poly = " ".join(pts)
    s.append(f'<polyline points="{poly}" fill="none" stroke="{BLUE}" '
             f'stroke-width="14" opacity="0.22" stroke-linecap="round"/>')
    s.append(f'<polyline points="{poly}" fill="none" stroke="{BLUE}" '
             f'stroke-width="2.5"/>')

    # curve label with a leader line
    lq = 0.855
    s.append(f'<line x1="{qx(lq):.1f}" y1="{ay(sigma(lq)):.1f}" '
             f'x2="{qx(0.815):.1f}" y2="{ay(0.585):.1f}" stroke="{INK}" '
             f'stroke-width="2"/>')
    s.append(txt(qx(0.815), ay(0.665), "σ = √(6/5) · √(q(1−q))",
                 21, INK, "bold", anchor="middle"))
    s.append(txt(qx(0.815), ay(0.615), "n = 6 candidates in every pool",
                 18, GRAY, anchor="middle"))

    # the seven dots
    scale = 22.0 / math.sqrt(max(COUNTS_ALL))
    for k, cnt in enumerate(COUNTS_ALL):
        q = k / float(N_CAND)
        cx, cy = qx(q), ay(sigma(q))
        r = scale * math.sqrt(cnt)
        s.append(f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r:.1f}" '
                 f'fill="{INK}" stroke="white" stroke-width="2.5"/>')
        if k in (0, N_CAND):
            s.append(txt(cx, cy - r - 14, f"{cnt}", 20, INK, "bold",
                         anchor="middle"))
        else:
            s.append(txt(cx, cy + r + 26, f"{cnt}", 20, INK, "bold",
                         anchor="middle"))

    # ---------------- shared x axis: pools as chips ----------------
    s.append(f'<line x1="{AXIS_X}" y1="{AY0}" x2="{PX1 + 46}" y2="{AY0}" '
             f'stroke="{INK}" stroke-width="2.5"/>')
    for k in range(N_CAND + 1):
        cx = qx(k / float(N_CAND))
        s.append(chip_pool(cx, AY0 + 22, k))
        s.append(txt(cx, AY0 + 66, f"{k} of 6", 19, INK, "bold",
                     anchor="middle"))
        s.append(txt(cx, AY0 + 90, f"q = {k / 6.0:.3f}", 18, GRAY,
                     anchor="middle"))
        s.append(f'<line x1="{cx:.1f}" y1="{BTOP - 12}" x2="{cx:.1f}" '
                 f'y2="{BY0}" stroke="{GRAY}" stroke-width="1" '
                 f'opacity="0.25"/>')
    s.append(txt(AXIS_X - 12, AY0 + 34,
                 "one pool:", 19, INK, "bold", anchor="end"))
    for i, line in enumerate(("how many of its", "six answers the",
                              "judge scored 1")):
        s.append(txt(AXIS_X - 12, AY0 + 58 + i * 22, line, 17, GRAY,
                     anchor="end"))

    # ---------------- panel B ----------------
    s.append(txt(58, 972, "Selection moves pools along that same axis, "
                          "towards the ends where the curve is low",
                 24, INK, "bold"))
    t, _ = text_block(
        58, 1000,
        "The same seven positions, now counted. Unanimous pools rise from "
        f"{ends_r1 * 100:.1f}% of prompt-rounds in round 1 to "
        f"{ends_r4 * 100:.1f}% in round 4; rounds 2 and 3 lie between. "
        "Numbers over the bars are the change in pool count.",
        19, 106, color=GRAY)
    s.append(t)

    for tick in (0.0, 0.10, 0.20, 0.30):  # noqa: E501
        yy = by(tick)
        s.append(f'<line x1="{AXIS_X}" y1="{yy:.1f}" x2="{PX1 + 46}" '
                 f'y2="{yy:.1f}" stroke="{GRAY}" stroke-width="1" '
                 f'opacity="0.3"/>')
        s.append(txt(AXIS_X - 12, yy + 7, f"{tick * 100:.0f}%", 19, GRAY,
                     anchor="end"))
    s.append(f'<line x1="{AXIS_X}" y1="{BTOP}" x2="{AXIS_X}" y2="{BY0}" '
             f'stroke="{GRAY}" stroke-width="2"/>')
    s.append(f'<line x1="{AXIS_X}" y1="{BY0}" x2="{PX1 + 46}" y2="{BY0}" '
             f'stroke="{INK}" stroke-width="2.5"/>')
    s.append(f'<text x="86" y="{(BTOP + BY0) / 2:.0f}" font-family="{FONT}" '
             f'font-size="20" fill="{INK}" text-anchor="middle" '
             f'transform="rotate(-90 86 {(BTOP + BY0) / 2:.0f})">'
             f'share of that round’s {per_round_n} pools</text>')

    bw, gap = 38, 5
    for k in range(N_CAND + 1):
        cx = qx(k / float(N_CAND))
        c1, c4 = COUNTS_BY_ROUND[1][k], COUNTS_BY_ROUND[4][k]
        s1, s4 = c1 / per_round_n, c4 / per_round_n
        x1 = cx - gap / 2.0 - bw
        x4 = cx + gap / 2.0
        s.append(f'<rect x="{x1:.1f}" y="{by(s1):.1f}" width="{bw}" '
                 f'height="{BY0 - by(s1):.1f}" rx="4" fill="white" '
                 f'stroke="{INK}" stroke-width="2.5"/>')
        s.append(f'<rect x="{x4:.1f}" y="{by(s4):.1f}" width="{bw}" '
                 f'height="{BY0 - by(s4):.1f}" rx="4" fill="{BLUE}"/>')
        dlt = c4 - c1
        sign = "+" if dlt > 0 else ("−" if dlt < 0 else "±")
        top = min(by(s1), by(s4))
        s.append(txt(cx, top - 14, f"{sign}{abs(dlt)}", 20, INK,
                     "bold" if abs(dlt) >= 20 else "normal", anchor="middle"))

    # in-figure condition lines: the two bars of the tallest pair say which
    # round they are, written along the bar itself -- no colour legend
    ktall = max(range(N_CAND + 1), key=lambda k: COUNTS_BY_ROUND[1][k])
    cxt = qx(ktall / float(N_CAND))
    for dx, label, col in ((-gap / 2.0 - bw / 2.0, "round 1", INK),
                           (gap / 2.0 + bw / 2.0, "round 4", "white")):
        lx3, ly3 = cxt + dx + 7, BY0 - 14
        s.append(f'<text x="{lx3:.1f}" y="{ly3}" font-family="{FONT}" '
                 f'font-size="20" font-weight="bold" fill="{col}" '
                 f'transform="rotate(-90 {lx3:.1f} {ly3})">{label}</text>')

    # outward arrows
    s.append(arrow(qx(0.34), BY0 + 40, qx(0.03), BY0 + 40, 4, INK))
    s.append(arrow(qx(0.66), BY0 + 40, qx(0.97), BY0 + 40, 4, INK))
    s.append(txt(qx(0.5), BY0 + 46,
                 "mass leaves the middle", 20, INK, "bold",
                 anchor="middle"))

    # ---------------- right column, box 1: the check ----------------
    b1y, b1h = 430, 520
    s.append(box(RX0, b1y, RW, b1h, KEY_FILL))
    s.append(txt(RX0 + 26, b1y + 46, "Arithmetic, not a fit", 25, INK, "bold"))
    s.append(txt(RX0 + RW / 2, b1y + 104,
                 "σ = √( n / (n−1) ) · √( q(1−q) )",
                 28, INK, "bold", anchor="middle"))
    t, yy = text_block(
        RX0 + 26, b1y + 148,
        "This is what the sample standard deviation of n numbers that are all "
        "0 or 1 evaluates to. Nothing was fitted, and nothing else could have "
        "come out.",
        19, 50, color=INK)
    s.append(t)
    t, yy = text_block(
        RX0 + 26, yy + 24,
        f"Checked on the corpus rather than asserted: {bid['rows_checked']:,} "
        f"of {n_rows:,} rows, all of them binary-scored "
        f"({d['binary_share_of_rows'] * 100:.0f}%). Largest gap between a "
        f"measured σ and the formula:",
        19, 50, color=INK)
    s.append(t)
    s.append(txt(RX0 + 26, yy + 44,
                 f"{bid['max_absolute_deviation']:.1e}".replace("e-16", " × 10⁻¹⁶"),
                 27, RED, "bold"))
    t, yy = text_block(
        RX0 + 26, yy + 82,
        f"One pixel of the plot at left is {px_per_sigma:.4f} of spread. That "
        "gap is fourteen orders of magnitude smaller — it is floating-point "
        "zero, not a small error.",
        19, 50, color=GRAY)
    s.append(t)

    # ---------------- right column, box 2: by round ----------------
    b2y, b2h = 984, 396
    s.append(box(RX0, b2y, RW, b2h, "white", INK, 2.5))
    s.append(txt(RX0 + 26, b2y + 42, "What each round of selection did",
                 25, INK, "bold"))
    col0 = RX0 + 26
    colx = [RX0 + 286 + i * 64 for i in range(4)]
    s.append(txt(col0, b2y + 80, "round", 19, GRAY))
    for i, c in enumerate(colx):
        s.append(txt(c, b2y + 80, str(i + 1), 19, GRAY, anchor="middle"))
    table = [
        ("pool mean q", [pm[r]["mean"] for r in rounds], False),
        ("distance of q from 0.5", [dh[r]["mean"] for r in rounds], True),
        ("spread σ", [sp[r]["mean"] for r in rounds], True),
    ]
    ry = b2y + 118
    for label, vals, bold in table:
        s.append(txt(col0, ry, label, 19, INK, "bold" if bold else "normal"))
        for c, v in zip(colx, vals):
            s.append(txt(c, ry, f"{v:.3f}", 20, INK,
                         "bold" if bold else "normal", anchor="middle"))
        ry += 40
    s.append(f'<line x1="{col0}" y1="{ry - 26}" x2="{RX0 + RW - 26}" '
             f'y2="{ry - 26}" stroke="{GRAY}" stroke-width="1" opacity="0.5"/>')
    t, yy = text_block(
        col0, ry + 8,
        f"{per_round_n} pools per round. The mean itself barely moves, "
        "because different runs polarise in opposite directions; what rises "
        "every round is the distance from the middle, and spread falls as the "
        "mechanical consequence.",
        19, 50, color=INK)
    s.append(t)

    # ---------------- footer ----------------
    t, yy = text_block(
        58, 1420,
        "Round counts selection steps, not time: taken alone the round index "
        f"accounts for {dec['round_share']:.3f} of the variance in pool means, "
        f"against {dec['prompt_share']:.3f} for the prompt and "
        f"{dec['run_share']:.3f} for the run (these overlap and do not sum to "
        "1). The polarisation above is done by selection, not by a clock.",
        18, 168, color=GRAY)
    s.append(t)
    t, _ = text_block(
        58, yy + 8,
        "Corpus: "
        f"{n_rows:,} prompt-rounds — {d['n_runs']} runs × "
        f"{d['n_prompts']} distinct prompts × 4 rounds, six candidates "
        "per pool. The same prompts give the same pool means across entirely "
        "different runs (split-half correlation "
        f"{stab['split_half_correlation_mean']:+.3f} "
        f"[{stab['ci_lo']:+.3f}, {stab['ci_hi']:+.3f}] over "
        f"{stab['n_splits']} random splits of the runs), so q — and "
        "therefore σ — is a property of the item, not noise. "
        "Graded candidate scores would be a different question, and this "
        "corpus contains none.",
        18, 168, color=GRAY)
    s.append(t)

    return svg_doc(W, H, "\n".join(s))


if __name__ == "__main__":
    out = os.path.join(HERE, "spread-is-the-mean.svg")
    with open(out, "w") as fh:
        fh.write(build())
    print("wrote", out)
