"""Test a simple conversion model for round-to-round candidate spread.

The evolving state is the distribution of candidates generated by the model,
not the round index. Per round:

  selector_gap       = kept_mean - whole_pool_mean
  pool_supply_shift  = whole_pool_mean - own_generated_mean
  training_displacement = kept_mean - own_generated_mean
                        = selector_gap + pool_supply_shift

Agreement converts offered spread into selector gap:
  selector_gap ~= 0.96 * rho * offered_spread.

Training displacement then moves the mean of the model's own generated pool.
On the binary risk axis, moving that mean toward or away from a 0/1 boundary
changes total Bernoulli variance q(1-q), which predicts next-round own-source
within-prompt spread. The continuous self-report axis is reported separately;
the same headroom conversion does not transport there.

The script compares this two-stage conversion chain with a spread-persistence
baseline under leave-one-run-out and leave-one-condition-out validation. It
also reports the exact within-source / between-source variance split for mixed
pools.

Run:    uv run python scripts/analysis_spread_conversion_model.py
Writes: experiments/spread_conversion_model.json
"""

import json
import math
import os
from collections import defaultdict

import numpy as np


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INPUT = os.path.join(ROOT, "experiments", "spread_util_unified.json")
OUTPUT = os.path.join(ROOT, "experiments", "spread_conversion_model.json")
FACTOR = 0.96


def run_key(r):
    return (r["cond"], r["seed"], r["source"])


def centrality(q):
    return q * (1.0 - q)


def ols(xs, ys):
    x = np.asarray(xs, float)
    y = np.asarray(ys, float)
    if len(x) < 3 or np.std(x) < 1e-12:
        return None
    slope, intercept = np.polyfit(x, y, 1)
    pred = intercept + slope * x
    return {
        "n": int(len(x)),
        "slope": float(slope),
        "intercept": float(intercept),
        "r": float(np.corrcoef(x, y)[0, 1]),
        "r2": float(1.0 - np.sum((y - pred) ** 2) / np.sum((y - np.mean(y)) ** 2)),
        "mae": float(np.mean(np.abs(y - pred))),
        "rmse": float(np.sqrt(np.mean((y - pred) ** 2))),
    }


def prediction_metrics(actual, predicted):
    y = np.asarray(actual, float)
    p = np.asarray(predicted, float)
    denom = np.sum((y - np.mean(y)) ** 2)
    return {
        "n": int(len(y)),
        "r2": float(1.0 - np.sum((y - p) ** 2) / denom) if denom > 0 else None,
        "mae": float(np.mean(np.abs(y - p))),
        "rmse": float(np.sqrt(np.mean((y - p) ** 2))),
        "r": float(np.corrcoef(y, p)[0, 1]) if len(y) >= 3 and np.std(p) > 0 else None,
    }


def rounded(value):
    if isinstance(value, dict):
        return {k: rounded(v) for k, v in value.items()}
    if isinstance(value, list):
        return [rounded(v) for v in value]
    if isinstance(value, float):
        return round(value, 6)
    return value


def slices(rows):
    return {
        "all": rows,
        "binary-risk-axis": [r for r in rows if r["axis"] == "risk"],
        "continuous-selfreport-axis": [r for r in rows if r["axis"] == "selfreport"],
        "self-only": [r for r in rows if r["composition"] == "self-only"],
        "mixed": [r for r in rows if r["composition"] != "self-only"],
        "binary-risk-self-only": [
            r for r in rows if r["axis"] == "risk" and r["composition"] == "self-only"
        ],
        "binary-risk-mixed": [
            r for r in rows if r["axis"] == "risk" and r["composition"] != "self-only"
        ],
        "base-mixed": [r for r in rows if r["composition"] == "base-mixed"],
        "peer-mixed": [r for r in rows if r["composition"] == "peer-mixed"],
    }


def make_transitions(records):
    by_run = defaultdict(dict)
    for r in records:
        by_run[run_key(r)][r["round"]] = r
    out = []
    for key, rounds in by_run.items():
        for k, r in rounds.items():
            if k + 1 not in rounds:
                continue
            nxt = rounds[k + 1]
            q = r["own_mean"]
            q_next = nxt["own_mean"]
            s = r["own_spread"]
            s_next = nxt["own_spread"]
            d = dict(r)
            d.update(
                run_key="|".join(map(str, key)),
                condition=r["cond"],
                q=q,
                q_next=q_next,
                delta_q=q_next - q,
                own_spread=s,
                own_spread_next=s_next,
                delta_own_spread=s_next - s,
                delta_own_centrality=centrality(q_next) - centrality(q),
            )
            if r.get("rho") is not None:
                d["factorized_selector_gap"] = FACTOR * r["rho"] * r["spread"]
                d["factorized_training_displacement"] = (
                    r["pool_supply_shift"] + d["factorized_selector_gap"]
                )
            out.append(d)
    return out


def fit_chain(train, gap_key):
    usable = [r for r in train if r.get(gap_key) is not None]
    q_fit = ols([r[gap_key] for r in usable], [r["delta_q"] for r in usable])
    geometry_fit = ols(
        [r["delta_own_centrality"] for r in usable],
        [r["delta_own_spread"] for r in usable],
    )
    ar_fit = ols([r["own_spread"] for r in usable], [r["own_spread_next"] for r in usable])
    return q_fit, geometry_fit, ar_fit


def predict_chain(row, q_fit, geometry_fit):
    dq_hat = q_fit["intercept"] + q_fit["slope"] * row["_gap_value"]
    # Both the score mean and the SD of binary scores have known support.
    q_next_hat = float(np.clip(row["q"] + dq_hat, 0.0, 1.0))
    dc_hat = centrality(q_next_hat) - centrality(row["q"])
    spread_hat = row["own_spread"] + geometry_fit["intercept"] + geometry_fit["slope"] * dc_hat
    return float(np.clip(spread_hat, 0.0, 0.5))


def cross_validate(rows, gap_key, holdout):
    usable = [r for r in rows if r.get(gap_key) is not None]
    predictions = []
    ar_predictions = []
    actual = []
    groups = sorted({r[holdout] for r in usable})
    for group in groups:
        train = [r for r in usable if r[holdout] != group]
        test = [r for r in usable if r[holdout] == group]
        q_fit, geometry_fit, ar_fit = fit_chain(train, gap_key)
        if not q_fit or not geometry_fit or not ar_fit:
            continue
        for r in test:
            row = dict(r, _gap_value=r[gap_key])
            predictions.append(predict_chain(row, q_fit, geometry_fit))
            ar_predictions.append(float(np.clip(
                ar_fit["intercept"] + ar_fit["slope"] * r["own_spread"],
                0.0,
                0.5,
            )))
            actual.append(r["own_spread_next"])
    return {
        "conversion_chain": prediction_metrics(actual, predictions),
        "spread_persistence": prediction_metrics(actual, ar_predictions),
    }


def conversion_results(transitions, gap_key):
    out = {}
    for name, rows in slices(transitions).items():
        usable = [r for r in rows if r.get(gap_key) is not None]
        if len(usable) < 10:
            continue
        q_fit, geometry_fit, ar_fit = fit_chain(usable, gap_key)
        out[name] = {
            "n_transitions": len(usable),
            "stage_1_delta_own_mean_vs_training_displacement": q_fit,
            "stage_2_delta_own_spread_vs_delta_headroom": geometry_fit,
            "persistence_fit": ar_fit,
            "leave_one_run_out": cross_validate(usable, gap_key, "run_key"),
            "leave_one_condition_out": cross_validate(usable, gap_key, "condition"),
        }
    return out


def mixed_variance_decomposition(records):
    out = {}
    for composition in ("base-mixed", "peer-mixed"):
        rows = [r for r in records if r["composition"] == composition]
        if not rows:
            continue
        mean_spread = float(np.mean([r["spread"] for r in rows]))
        within = float(np.mean([r["within_source_spread"] for r in rows]))
        between = float(np.mean([r["between_source_spread_increment"] for r in rows]))
        mean_total_variance = float(np.mean([r["mean_item_variance"] for r in rows]))
        mean_within_variance = float(np.mean([r["within_source_var"] for r in rows]))
        mean_between_variance = float(np.mean([r["between_source_var"] for r in rows]))
        out[composition] = {
            "n_rounds": len(rows),
            "mean_total_within_prompt_variance": mean_total_variance,
            "mean_within_source_variance": mean_within_variance,
            "mean_between_source_variance": mean_between_variance,
            "between_variance_share_of_mean_total": mean_between_variance / mean_total_variance,
            "mean_total_spread": mean_spread,
            "mean_sd_if_between_source_variance_removed_per_prompt": within,
            "mean_sd_increment_from_between_source_variance": between,
            "sd_increment_share_of_mean_total_spread": between / mean_spread,
        }
    errors = [
        abs(r["spread"] - r["mixture_spread_reconstructed"])
        for r in records if r["composition"] != "self-only"
    ]
    out["max_reconstruction_rounding_error"] = max(errors)
    return out


def main():
    data = json.load(open(INPUT))
    records = data["records"]
    transitions = make_transitions(records)

    drift_models = {}
    for name, rows in slices(records).items():
        if len(rows) < 3:
            continue
        drift_models[name] = {
            "whole_pool_selector_gap": ols([r["gap"] for r in rows], [r["drift"] for r in rows]),
            "self_relative_training_displacement": ols(
                [r["self_relative_gap"] for r in rows], [r["drift"] for r in rows]
            ),
            "behavioral_pull": ols([r["pull"] for r in rows], [r["drift"] for r in rows]),
        }

    factor_rows = [r for r in records if r.get("rho") is not None]
    for r in factor_rows:
        r["factorized_selector_gap"] = FACTOR * r["rho"] * r["spread"]
        r["factorized_training_displacement"] = (
            r["pool_supply_shift"] + r["factorized_selector_gap"]
        )
        r["factorized_behavioral_pull"] = (
            r["factorized_training_displacement"] + r["generator_calibration_residual"]
        )

    factorization = {}
    for name, rows in slices(factor_rows).items():
        if len(rows) < 5:
            continue
        factorization[name] = {
            "predicted_vs_actual_training_displacement": ols(
                [r["factorized_training_displacement"] for r in rows],
                [r["self_relative_gap"] for r in rows],
            ),
            "drift_vs_factorized_training_displacement": ols(
                [r["factorized_training_displacement"] for r in rows],
                [r["drift"] for r in rows],
            ),
            "drift_vs_factorized_behavioral_pull": ols(
                [r["factorized_behavioral_pull"] for r in rows],
                [r["drift"] for r in rows],
            ),
        }

    mixed = [r for r in records if r["composition"] != "self-only"]
    identities = {
        "max_abs_training_displacement_identity_error": max(
            abs(r["self_relative_gap"] - r["gap"] - r["pool_supply_shift"])
            for r in records
        ),
        "max_abs_pull_identity_error": max(
            abs(r["pull"] - r["self_relative_gap"] - r["generator_calibration_residual"])
            for r in records
        ),
        "mixed_own_generated_mean_vs_behavioral_value": ols(
            [r["own_mean"] for r in mixed], [r["value"] for r in mixed]
        ),
    }

    out = {
        "description": "Selection-to-spread conversion model using the model's own generated pool as the evolving state.",
        "definitions": {
            "within_prompt_spread": (
                "mean over prompts j of sqrt(mean over observed candidates k "
                "of (x_jk-xbar_j)^2); population SD, ddof=0, not pooled across prompts"
            ),
            "selector_gap": "kept_mean - whole_pool_mean; sorting inside the offered pool",
            "pool_supply_shift": "whole_pool_mean - own_generated_mean; displacement introduced by outside supply",
            "training_displacement": "kept_mean - own_generated_mean = selector_gap + pool_supply_shift",
            "behavioral_pull": "kept_mean - behavioral_value = training_displacement + generator_calibration_residual",
            "own_headroom": (
                "q*(1-q), where q is the own-candidate mean; exact total variance "
                "only on the binary risk score, not the continuous self-report score"
            ),
        },
        "counts": {
            "rounds": len(records),
            "runs": len({run_key(r) for r in records}),
            "transitions": len(transitions),
            "binary_risk_transitions": sum(r["axis"] == "risk" for r in transitions),
            "continuous_selfreport_transitions": sum(
                r["axis"] == "selfreport" for r in transitions
            ),
        },
        "identity_checks": identities,
        "drift_coordinate_comparison": drift_models,
        "factorized_force": factorization,
        "observed_training_displacement_chain": conversion_results(
            transitions, "self_relative_gap"
        ),
        "factorized_training_displacement_chain": conversion_results(
            transitions, "factorized_training_displacement"
        ),
        "mixed_pool_variance_decomposition": mixed_variance_decomposition(records),
    }
    out = rounded(out)
    with open(OUTPUT, "w") as f:
        json.dump(out, f, indent=1)

    print(f"{len(records)} rounds / {len(transitions)} transitions -> {OUTPUT}")
    for name in ("binary-risk-axis", "continuous-selfreport-axis", "binary-risk-mixed"):
        dm = out["drift_coordinate_comparison"][name]
        print(name, "drift r:",
              dm["whole_pool_selector_gap"]["r"],
              dm["self_relative_training_displacement"]["r"],
              dm["behavioral_pull"]["r"])
        cv = out["observed_training_displacement_chain"][name]["leave_one_run_out"]
        print(name, "next own spread LORO R2:",
              cv["conversion_chain"]["r2"], cv["spread_persistence"]["r2"])


if __name__ == "__main__":
    main()
