#!/usr/bin/env python3
"""Build the entropy synthesis figure from the reconstructed JSON analysis.

Regenerate from the repository root with:
  python3 docs/figures/src/synthesis_entropy_and_actionable_variation.py

Stdlib only. The numerical source is generated by
scripts/analysis_entropy_synthesis.py from the saved experiment artifacts.
"""

from __future__ import annotations

import html
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "experiments" / "entropy_synthesis_analysis.json"
OUTPUT = ROOT / "docs" / "figures" / "synthesis_entropy_and_actionable_variation.svg"

W, H = 1680, 1180
INK = "#17212b"
GRAY = "#647180"
LIGHT = "#dce2e8"
PANEL = "#fbfcfd"
BLUE = "#2867b5"
RED = "#b5342c"
GREEN = "#3a7d44"
PURPLE = "#7952a8"
AMBER = "#b87812"
FONT = "Helvetica, Arial, sans-serif"


def esc(value: object) -> str:
    return html.escape(str(value))


def text(x, y, value, size=20, color=INK, weight="normal", anchor="start"):
    return (
        f'<text x="{x:.1f}" y="{y:.1f}" text-anchor="{anchor}" '
        f'font-family="{FONT}" font-size="{size}" font-weight="{weight}" '
        f'fill="{color}">{esc(value)}</text>'
    )


def line(x1, y1, x2, y2, color=LIGHT, width=1.5, dash=None):
    dashed = f' stroke-dasharray="{dash}"' if dash else ""
    return (
        f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
        f'stroke="{color}" stroke-width="{width}"{dashed}/>'
    )


def circle(x, y, r, fill, stroke="white", width=1.5):
    return (
        f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r:.1f}" fill="{fill}" '
        f'stroke="{stroke}" stroke-width="{width}"/>'
    )


def rect(x, y, w, h, fill=PANEL, stroke=LIGHT, radius=16, width=1.5):
    return (
        f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" '
        f'rx="{radius}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>'
    )


def polyline(points, color, width=3.5):
    coords = " ".join(f"{x:.1f},{y:.1f}" for x, y in points)
    return f'<polyline points="{coords}" fill="none" stroke="{color}" stroke-width="{width}"/>'


def panel_heading(parts, x, y, label, title_value, note):
    parts.append(text(x, y, label, 18, BLUE, "bold"))
    parts.append(text(x + 34, y, title_value, 24, INK, "bold"))
    parts.append(text(x + 34, y + 28, note, 17, GRAY))


def chart_axes(parts, x0, y0, w, h, ymax, yticks, ylabel):
    parts.append(line(x0, y0, x0, y0 + h, GRAY, 1.4))
    parts.append(line(x0, y0 + h, x0 + w, y0 + h, GRAY, 1.4))
    for tick in yticks:
        py = y0 + h - (tick / ymax) * h
        parts.append(line(x0, py, x0 + w, py, LIGHT, 1.0))
        parts.append(text(x0 - 10, py + 6, f"{tick:.1f}", 15, GRAY, anchor="end"))
    parts.append(
        f'<text x="{x0 - 57:.1f}" y="{y0 + h / 2:.1f}" text-anchor="middle" '
        f'transform="rotate(-90 {x0 - 57:.1f} {y0 + h / 2:.1f})" '
        f'font-family="{FONT}" font-size="16" fill="{GRAY}">{esc(ylabel)}</text>'
    )


def draw_mixing(parts, data):
    x, y, w, h = 55, 155, 755, 410
    parts.append(rect(x, y, w, h))
    panel_heading(
        parts,
        x + 24,
        y + 38,
        "A",
        "Fresh data rescues output entropy",
        "Five training rounds; dots are individual runs, lines are cell means (n=2).",
    )
    x0, y0, cw, ch = x + 94, y + 105, w - 130, h - 165
    chart_axes(parts, x0, y0, cw, ch, 1.2, [0.0, 0.4, 0.8, 1.2], "final token entropy")
    fractions = [0.25, 0.50, 0.75, 1.00]
    colors = {"base": BLUE, "sycophancy": RED}
    names = {"base": "base model", "sycophancy": "sycophancy model"}
    for i, fraction in enumerate(fractions):
        px = x0 + i * cw / 3
        parts.append(text(px, y0 + ch + 25, f"{int(100*fraction)}%", 16, GRAY, anchor="middle"))
    parts.append(text(x0 + cw / 2, y0 + ch + 51, "share of training data generated by the model", 16, GRAY, anchor="middle"))

    for organism in ("base", "sycophancy"):
        points = []
        for i, fraction in enumerate(fractions):
            group = data[f"{organism}/lambda_{int(fraction*100)}"]["entropy_final"]
            px = x0 + i * cw / 3
            mean_y = y0 + ch - (group["mean"] / 1.2) * ch
            min_y = y0 + ch - (group["min"] / 1.2) * ch
            max_y = y0 + ch - (group["max"] / 1.2) * ch
            parts.append(line(px, min_y, px, max_y, colors[organism], 1.8))
            parts.append(line(px - 6, min_y, px + 6, min_y, colors[organism], 1.8))
            parts.append(line(px - 6, max_y, px + 6, max_y, colors[organism], 1.8))
            parts.append(circle(px, min_y, 4.7, colors[organism]))
            parts.append(circle(px, max_y, 4.7, colors[organism]))
            points.append((px, mean_y))
        parts.append(polyline(points, colors[organism]))
        for px, py in points:
            parts.append(circle(px, py, 7.0, colors[organism]))

    ly = y + 94
    parts.append(line(x + 185, ly - 5, x + 220, ly - 5, BLUE, 4))
    parts.append(text(x + 230, ly, names["base"], 16, GRAY))
    parts.append(line(x + 395, ly - 5, x + 430, ly - 5, RED, 4))
    parts.append(text(x + 440, ly, names["sycophancy"], 16, GRAY))


def draw_dose(parts, analysis):
    x, y, w, h = 830, 155, 795, 410
    parts.append(rect(x, y, w, h))
    panel_heading(
        parts,
        x + 24,
        y + 38,
        "B",
        "More optimizer updates accelerate entropy loss",
        "Per round: 5, 10, or 20 AdamW updates; effective batch 16. Mean ± SE across 12 runs.",
    )
    x0, y0, cw, ch = x + 90, y + 105, w - 130, h - 165
    chart_axes(parts, x0, y0, cw, ch, 0.5, [0.0, 0.1, 0.2, 0.3, 0.4, 0.5], "token entropy")
    rounds = [0, 1, 3, 5]
    xpositions = [x0 + i * cw / 3 for i in range(4)]
    for px, round_ in zip(xpositions, rounds):
        parts.append(text(px, y0 + ch + 25, round_, 16, GRAY, anchor="middle"))
    parts.append(text(x0 + cw / 2, y0 + ch + 51, "training round", 16, GRAY, anchor="middle"))

    colors = {5: GREEN, 10: AMBER, 20: PURPLE}
    round0 = analysis["organism_round0_entropy"]
    for dose in (5, 10, 20):
        values = [(round0, 0.0)]
        for round_ in (1, 3, 5):
            stats = analysis["groups"][f"dose_{dose}/round_{round_}"]["entropy"]
            values.append((stats["mean"], stats["se"]))
        points = []
        for px, (mean, se) in zip(xpositions, values):
            py = y0 + ch - (mean / 0.5) * ch
            ey1 = y0 + ch - ((mean - se) / 0.5) * ch
            ey2 = y0 + ch - ((mean + se) / 0.5) * ch
            if se:
                parts.append(line(px, ey1, px, ey2, colors[dose], 1.7))
            points.append((px, py))
        parts.append(polyline(points, colors[dose]))
        for px, py in points:
            parts.append(circle(px, py, 6.5, colors[dose]))
        last_x, last_y = points[-1]
        parts.append(text(last_x + 12, last_y + 5, f"{dose} updates", 16, colors[dose], "bold"))


def meter(parts, x, y, w, value, maximum, color, label):
    parts.append(text(x, y - 8, label, 15, GRAY))
    parts.append(rect(x, y, w, 13, "#e8ecf0", "#e8ecf0", 6, 0))
    width = max(0.0, min(w, w * value / maximum))
    parts.append(rect(x, y, width, 13, color, color, 6, 0))


def draw_distinction(parts, analysis):
    x, y, w, h = 55, 590, 1570, 425
    parts.append(rect(x, y, w, h))
    panel_heading(
        parts,
        x + 24,
        y + 38,
        "C",
        "Token entropy does not tell us whether selection can move the value",
        "OLMo risk model and Qwen insecure-code model: the judge needs value-axis variation and a nonzero kept-minus-pool gap.",
    )

    parts.append(text(x + 500, y + 105, "generic token entropy", 17, GRAY, "bold", anchor="middle"))
    parts.append(text(x + 885, y + 105, "spread on selected value axis", 17, GRAY, "bold", anchor="middle"))
    parts.append(text(x + 1270, y + 105, "measured value trajectory", 17, GRAY, "bold", anchor="middle"))

    rich = analysis["olmo_material_rich_reversal"]
    inert = analysis["olmo_target_axis_inert_rail"]
    twin = analysis["qwen_matched_selfonly"]
    mixed = analysis["qwen_matched_external_supply"]
    rows = [
        {
            "name": "risk model",
            "subname": "usable risk-axis answers",
            "entropy": sum(rich["generic_token_entropy"]) / len(rich["generic_token_entropy"]),
            "spread": sum(rich["target_axis_pool_spread"]) / len(rich["target_axis_pool_spread"]),
            "trajectory": "0.917 → 0.094",
            "outcome": "moves",
            "color": GREEN,
        },
        {
            "name": "risk model",
            "subname": "same entropy, no risk-axis variation",
            "entropy": sum(inert["generic_token_entropy"]) / len(inert["generic_token_entropy"]),
            "spread": 0.0,
            "trajectory": "1.000 → 1.000",
            "outcome": "stuck",
            "color": GRAY,
        },
        {
            "name": "insecure-code model",
            "subname": "self-only answers",
            "entropy": sum(sum(r["generic_token_entropy"]) for r in twin) / sum(len(r["generic_token_entropy"]) for r in twin),
            "spread": 0.0,
            "trajectory": "0.627 → 0.625",
            "outcome": "stuck",
            "color": GRAY,
        },
        {
            "name": "insecure-code model",
            "subname": "add base-model answers",
            "entropy": sum(r["generic_token_entropy"][1] for r in mixed) / len(mixed),
            "spread": sum(r["target_axis_pool_spread"][0] for r in mixed) / len(mixed),
            "trajectory": "0.627 → 0.000",
            "outcome": "moves",
            "color": GREEN,
        },
    ]

    row_y = [y + 142, y + 210, y + 278, y + 346]
    for idx, (row, ry) in enumerate(zip(rows, row_y)):
        if idx == 2:
            parts.append(line(x + 22, ry - 23, x + w - 22, ry - 23, LIGHT, 1.2, "5,5"))
        parts.append(text(x + 28, ry + 1, row["name"], 16, INK, "bold"))
        parts.append(text(x + 28, ry + 21, row["subname"], 15, GRAY))
        meter(parts, x + 365, ry, 270, row["entropy"], 0.8, BLUE, f'{row["entropy"]:.3f}')
        meter(parts, x + 750, ry, 270, row["spread"], 0.35, PURPLE, f'{row["spread"]:.3f}')
        parts.append(text(x + 1135, ry + 10, row["trajectory"], 22, row["color"], "bold"))
        parts.append(text(x + 1400, ry + 9, row["outcome"], 17, row["color"], "bold", anchor="middle"))

    parts.append(text(x + 365, y + h - 20, "Bars have separate scales; they are not pooled into one metric.", 15, GRAY))


def draw_footer(parts):
    y = 1040
    parts.append(text(55, y, "Updated model", 18, BLUE, "bold"))
    boxes = [
        (205, 1018, 330, "token entropy", "generative health"),
        (650, 1018, 360, "value-axis spread", "actionable material"),
        (1125, 1018, 395, "selection gap", "predicts movement"),
    ]
    for bx, by, bw, title_value, subtitle in boxes:
        parts.append(rect(bx, by, bw, 90, "white", LIGHT, 14))
        parts.append(text(bx + bw / 2, by + 35, title_value, 21, INK, "bold", anchor="middle"))
        parts.append(text(bx + bw / 2, by + 64, subtitle, 16, GRAY, anchor="middle"))
    parts.append(line(535, 1063, 650, 1063, GRAY, 2.2))
    parts.append('<polygon points="650,1063 638,1057 638,1069" fill="#647180"/>')
    parts.append(text(592, 1048, "can affect", 14, GRAY, anchor="middle"))
    parts.append(line(1010, 1063, 1125, 1063, GRAY, 2.2))
    parts.append('<polygon points="1125,1063 1113,1057 1113,1069" fill="#647180"/>')
    parts.append(text(1068, 1048, "judge acts on", 14, GRAY, anchor="middle"))
    parts.append(text(840, 1152, "Entropy is upstream context; it is neither sufficient nor interchangeable with value-axis variation.", 18, INK, "bold", anchor="middle"))


def main():
    with SOURCE.open() as f:
        data = json.load(f)
    parts = [f'<rect width="{W}" height="{H}" fill="white"/>']
    parts.append(text(55, 60, "Entropy shapes the intervention window, but it is not the movement variable", 36, INK, "bold"))
    parts.append(text(55, 98, "Across saved self-training runs, data source and optimizer-update count control token entropy; selection still needs variation on the chosen value axis.", 20, GRAY))
    draw_mixing(parts, data["fresh_data_mixing_curve"]["groups"])
    draw_dose(parts, data["dose_gradient"])
    draw_distinction(parts, data["token_entropy_vs_actionable_value_axis_variation"])
    draw_footer(parts)
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
        f'font-family="{FONT}">\n' + "\n".join(parts) + "\n</svg>\n"
    )
    OUTPUT.write_text(svg)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
